
### Introducción a Python/Numpy

Probablemente ya vengan de ver varias de estas cosas (o parecidas), pero nunca viene mal un repaso de código. Recordar nuevamente, vamos a usar **Python 3**

Aclaraciones: 
Para poder instalar Python, en Linux probablemente no tengan que hacer nada más que 

```
sudo apt install python3
```
Para Windows, hay que hacer un poco más de laburo, pero la forma más sencilla de tener todo andando es instalando Anaconda: https://www.anaconda.com/products/individual#windows (elegir 64 bits). También se puede instalar Anaconda en Linux y no sería una mala idea si en el futuro quieren seguir trabajando con *Python o R*.

En Colab ya vienen muchas librerías instaladas, para poder ejecutar algunas cosas en sus entornos locales, va a ser necesario instalar al menos 3 librerías que vamos a usar bastante.

- Numpy (pip install numpy)
- Scipy (pip install scipy)
- Jupyter Notebooks (pip install jupyter)


In [ ]:
# Estructuras básicas de Python
variable = 4

lista = [1, 2, 3, 4]

tupla = (1, 2, 3)

conjunto = {1, 3, 3, 2}

texto = "holi"

diccionario = {
    "campo1": 1,
    "campo2": "segundo",
    "campo3": [1, 2, 3],
}

In [ ]:
lista[2]

3

In [ ]:
# bucles
# for nos permite hacer operaciones mientras dure el objeto
# sobre el cual estoy iterando (la definición de iterable
# de Python es un poco extensa)
for indice in range(10):
    print(indice)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# deposito numero en variable indice
indice = 0
# while deja de ejecutar cuando la clausula evalúa False
while indice < 10:
    print(indice)
    indice = indice + 1

0
1
2
3
4
5
6
7
8
9


In [ ]:
# if
for indice in range(10):
    # Si pasa algo, entonces ejecutá una acción
    if indice % 3 == 0:
        print(indice)
    # Si, en cambio, pasa otra cosa, ejecutá una acción
    elif indice % 3 == 1:
        print("si le restamos 1 lo imprimo...")
    # Si no pasó nada de lo anterior, ejecutá lo siguiente
    # Podemos hacer if -> else, no es necesario que exista un 'elif'
    else:
        print("sumale 1 y hablamos")

0
si le restamos 1 lo imprimo...
sumale 1 y hablamos
3
si le restamos 1 lo imprimo...
sumale 1 y hablamos
6
si le restamos 1 lo imprimo...
sumale 1 y hablamos
9


In [ ]:
# Definir funciones
def imprimir(texto="hola"):
    print(texto)

In [ ]:
imprimir("holi")

holi


In [ ]:
imprimir()

hola


### Pasemos a Numpy!


In [ ]:
import numpy as np
# Cada bicho con el que trabajemos se va a generar como un Numpy Array
# Un vector es un array de una dimension
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [ ]:
# Una matriz será un array de 2 dimensiones, que se va a hacer con listas dentro
# de otras listas, definiendo por filas.
np.array([[1., 0], [0, 1]])

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Tenemos algunas matrices y vectores de mucha fama, como la identidad
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Todos ceros (tupla de forma)
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Puedo hacer diferentes cosas con el array
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)
print("Elemento (1,1): {}".format(mat[0, 0]))
print("Segunda columna: {}".format(mat[:, 1]))
print("Primera fila: {}".format(mat[0, :]))
print("Filas y columnas de mat: {}".format(mat.shape))
print("Transpuesta de mat:\n{}".format(mat.T))
print("Otra forma de transponer:\n{}".format(np.transpose(mat)))

[[1 2 3]
 [4 5 6]]
Elemento (1,1): 1
Segunda columna: [2 5]
Primera fila: [1 2 3]
Filas y columnas de mat: (2, 3)
Transpuesta de mat:
[[1 4]
 [2 5]
 [3 6]]
Otra forma de transponer:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Práctico 1, ejercicio 1!!!
A00 = np.array([[1], [2]])
A01 = np.array([[3, 2], [1, 1]])
A10 = np.array([[-1]])
A11 = np.array([[0, 1]])

In [ ]:
print(A00)
print(A01)
print(A10)
print(A11)

[[1]
 [2]]
[[3 2]
 [1 1]]
[[-1]]
[[0 1]]


In [ ]:
A = np.block([[A00, A01], [A10, A11]])
A

array([[ 1,  3,  2],
       [ 2,  1,  1],
       [-1,  0,  1]])

In [ ]:
B00 = np.array([[1]])
B01 = np.array([[0, 1]])
B10 = np.array([[2], [-1]])
B11 = np.array([[1, 1], [2, 0]])

In [ ]:
B = np.block([[B00, B01], [B10, B11]])
B

array([[ 1,  0,  1],
       [ 2,  1,  1],
       [-1,  2,  0]])

In [ ]:
A @ B

array([[ 5,  7,  4],
       [ 3,  3,  3],
       [-2,  2, -1]])

###EXTRA
Por qué hacemos las cosas lo menos "elemento a elemento" posible?

In [ ]:
%%timeit
A @ B

The slowest run took 43.20 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.08 µs per loop


In [ ]:
%%timeit
C = np.empty((3, 3))
for fila in range(C.shape[0]):
    for columna in range(C.shape[1]):
        C[fila, columna] = np.dot(A[fila, :], B[:, columna])

The slowest run took 16.00 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 18.7 µs per loop


In [ ]:

C

array([[ 5.,  7.,  4.],
       [ 3.,  3.,  3.],
       [-2.,  2., -1.]])

In [ ]:
%%timeit
C = np.empty((3, 3))
for fila in range(C.shape[0]):
    for columna in range(C.shape[1]):
        C[fila, columna] = 0
        for idx in range(A.shape[1]):
            C[fila, columna] += A[fila, idx] * B[idx, columna]
            

10000 loops, best of 3: 31 µs per loop


In [ ]:
C

array([[ 5.,  7.,  4.],
       [ 3.,  3.,  3.],
       [-2.,  2., -1.]])

In [ ]:
whos

Variable      Type        Data/Info
-----------------------------------
A             ndarray     3x3: 9 elems, type `int64`, 72 bytes
A00           ndarray     2x1: 2 elems, type `int64`, 16 bytes
A01           ndarray     2x2: 4 elems, type `int64`, 32 bytes
A10           ndarray     1x1: 1 elems, type `int64`, 8 bytes
A11           ndarray     1x2: 2 elems, type `int64`, 16 bytes
A12           ndarray     2x2: 4 elems, type `int64`, 32 bytes
A21           ndarray     1x1: 1 elems, type `int64`, 8 bytes
A22           ndarray     1x2: 2 elems, type `int64`, 16 bytes
B             ndarray     3x3: 9 elems, type `int64`, 72 bytes
B00           ndarray     1x1: 1 elems, type `int64`, 8 bytes
B01           ndarray     1x2: 2 elems, type `int64`, 16 bytes
B10           ndarray     2x1: 2 elems, type `int64`, 16 bytes
B11           ndarray     2x2: 4 elems, type `int64`, 32 bytes
C             ndarray     3x3: 9 elems, type `float64`, 72 bytes
columna       int         2
conjunto      set  